// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8Dhj4GEIYkCJC30GnMM9c_qGQj9BQO5k',
    appId: '1:371888079966:web:0f5b9344648fdfd27460cf',
    messagingSenderId: '371888079966',
    projectId: 'printimate-44033',
    authDomain: 'printimate-44033.firebaseapp.com',
    storageBucket: 'printimate-44033.firebasestorage.app',
    measurementId: 'G-QGTDQ3HSFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKuDP0dJ2miTDr_hNC_oOHKSVgVMYeI4A',
    appId: '1:371888079966:android:d9c82121064eaf227460cf',
    messagingSenderId: '371888079966',
    projectId: 'printimate-44033',
    storageBucket: 'printimate-44033.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpXn5PBdTGv_oFGUwqhaVstfZXYdvW8fU',
    appId: '1:371888079966:ios:83d866c1a5c436a27460cf',
    messagingSenderId: '371888079966',
    projectId: 'printimate-44033',
    storageBucket: 'printimate-44033.firebasestorage.app',
    iosBundleId: 'com.printimate.printimateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpXn5PBdTGv_oFGUwqhaVstfZXYdvW8fU',
    appId: '1:371888079966:ios:83d866c1a5c436a27460cf',
    messagingSenderId: '371888079966',
    projectId: 'printimate-44033',
    storageBucket: 'printimate-44033.firebasestorage.app',
    iosBundleId: 'com.printimate.printimateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Dhj4GEIYkCJC30GnMM9c_qGQj9BQO5k',
    appId: '1:371888079966:web:935555eb787a89837460cf',
    messagingSenderId: '371888079966',
    projectId: 'printimate-44033',
    authDomain: 'printimate-44033.firebaseapp.com',
    storageBucket: 'printimate-44033.firebasestorage.app',
    measurementId: 'G-BYEX2ZPCY8',
  );
}
